dataset: 'YFCC'
checkpoint: ./weights/outdoor.pth
data_path: /mnt/nas_7/datasets/yfcc100M/
pairs_path: data/yfcc_test_pairs_with_gt.txt
seed: 18027
threshold: 0.25
if_outdoor: True
merge_new: True
if_local: False
