dataset: 'MegaDepth'
checkpoint: ./weights/outdoor.pth
data_path: /mnt/nas_7/datasets/yeweicai/MegaDepth/phoenix/S6/zl548/MegaDepth_v1/
pairs_path: /mnt/nas_7/datasets/nijunjie_changed_megadepth/easier_megadepth/megadepth_parameters/
seed: 18027
threshold: 0.25
